### ISSUE TITLE
Scroll the parent when options goes too much

### ISSUE THREAD

**Issue by void-arash-911** [vmcdesign/custom-select-wip#1]
Good work. this has a bad behavior(not a bug really). When list goes large(many options), so it causes scroll, so user needs to scroll the whole page to select an option at bottom instead of scroll the container.
This could be great if the parent ul tag has a max-height property.

**Comment by vmcdesign** [comment]
Thank you for bringing this to my attention!  I'm still working on this, and haven't committed any updates to the code yet, but I implemented your proposed fix behind the scenes.  I'd like your insight again when this project is considered finished.

**Comment by vmcdesign** [comment]
I went ahead and did as you suggested.  Thanks!
