### ISSUE TITLE
Close other lists when a new one is expanded/opened[option/suggestion]

### ISSUE THREAD

**Issue by void-arash-911** [vmcdesign/custom-select-wip#3]
You may implement the option, and let the dev either select or ignore this option using your API.

Once a new list is clicked, other(previous) list may be closed. CUrrently, if two lists clicked, both of them keep open. I think the default approach users expected is close the list once the primary focus gets lost.

**Comment by vmcdesign** [comment]
If you see the README, under "To Do," this was listed as one of the features I intended on implementing.  Either way, I finally got around to it and can cross this off my list!

**Comment by void-arash-911** [comment]
Yes, sorry, my bad.
